routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Removing/Avoiding Register & Password Reset functionality 
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});

Route::get('/password/reset', function() {
    return redirect('/login');
});

Route::post('/password/reset', function() {
    return redirect('/login');
});



Route::prefix('admin')->group(function () {

    Route::resource('about', 'AboutController', [
        'names' => 'about',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('advertise', 'AdvertiseController', [
        'names' => 'advertise',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('businessRegistration', 'BusinessRegistrationController', [
        'names' => 'businessRegistration',
        'except' => [
            'show',
        ]
    ]);

    Route::resource('businessCategory', 'BusinessCategoryController', [
        'names' => 'businessCategory',
        'except' => [
            'show',
        ]
    ]);


    Route::resource('coupon', 'CouponController', [
        'names' => 'coupon',
        'except' => [
            'show',
        ]
    ]);


     Route::resource('page', 'PageController', [
        'names' => 'page',
        'except' => [
            'show',
        ]
    ]);


    Route::post('imageUploadCK', 'PageController@imageUploadCK')->name('imageUploadCK');


    // Route for Show Change Password form and change user Password
    Route::get('changePassword', 'HomeController@showChangePassword')->name('showChangePassword');
    Route::post('changePassword', 'HomeController@changePassword')->name('changeDefaultPassword');
});

resources/views/admin/about-us/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit About Us')

@section('content')

<style>
.ck-editor__editable_inline {
    min-height: 400px;
}

.ck.ck-editor {
    max-width: 67rem;
}
</style>

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('about.index') }}" title="Go to About" class="tip-bottom">
        <i class="icon-home"></i>About</a>
    </div>
  </div>
<!--End-breadcrumbs-->

{{-- {{ dd($about)}} --}}

<div class="container-fluid margin-top-2">
    <form action="{{route('about.update', $about)}}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    @csrf
    @method('PATCH')

    <div class="widget-box">
      <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
        <h5>About Page Content</h5>
      </div>

    <div class="control-group">
        <label class="control-label">Banner Title :</label>
        <div class="controls">
          <input type="text" 
                 name="banner_title" 
                 class="span11" 
                 placeholder="Banner Title" 
                 value="{{old('banner_title', isset($about) ? $about->banner_title:'')}}" 
                 required />

          @error('banner_title')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>

    
      <div class="control-group">
        <label class="control-label">Short Description :</label>
        <div class="controls">
          <textarea class="span11" name="short_description" rows="5">{{old('short_description', isset($about) ? $about->short_description:'')}}</textarea>

          @error('short_description')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>


      <div class="control-group">
        <label class="control-label">Banner Image</label>
        <div class="controls">
          <input type="file" name="banner_image" accept="image/*" onchange="showBannerImage(this)" />

          @error('banner_image')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror

         <img src="{{  isset($about->banner_image) ? Storage::url($about->banner_image) : asset('adminAssets/img/default-org.png') }}"
                   id="AboutBannerImg"
                   class="frame frame-1"
                   title="Banner Image"
                   alt="banner_image">
        </div>

      </div>

       <div class="control-group">
        <label class="control-label">Page Content :</label>
        <div class="controls">
            <textarea name="content" id="About" cols="30" rows="10">{{ old("content", $about->content) }}</textarea>

          @error('content')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>

     <div class="form-actions">
         <button type="submit" class="btn btn-success margin-top-1">Update</button>
        <a href="{{ route('about.index') }}" class="btn btn-danger margin-top-1">Cancel</a>
      </div>
        
       
    </div>
    </form>
</div>



<script src="{{ asset('adminAssets/plugins/ckeditor5/ckeditor.js') }}"></script>


@include('admin.about-us.scripts')

@endsection

resources/views/admin/about-us/list.blade.php
@extends('layouts.master')

@section('title', 'About Us')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('about.index') }}" title="Go to About" class="tip-bottom">
        <i class="icon-home"></i> About</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  <div class="container-fluid">
        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5>About Us Content</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Short Description</th>
                  <th>Page Content</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                @foreach($abouts as $about)
                <tr class="odd gradeX">
                  <td class="align-center fifteen-width">
                      {{ $about->banner_title }}
                  </td>
                  <td class="align-center thirty-width">
                    {{ $about->short_description }}
                  </td>
                  <td class="thirty-width">
                      {!! $about->content !!}
                  </td>
                  
                  <td class="align-center ten-width">
                       <a href="{{ route('about.edit', $about) }}" class="btn btn-primary">Edit</a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
    </div>

@endsection

resources/views/admin/about-us/scripts.blade.php
<script>
    class MyUploadAdapter {
        constructor( loader ) {
            // The file loader instance to use during the upload. It sounds scary but do not
            // worry — the loader will be passed into the adapter later on in this guide.
            this.loader = loader;
        }

        // Starts the upload process.
        upload() {
            return this.loader.file
                .then( file => new Promise( ( resolve, reject ) => {
                    this._initRequest();
                    this._initListeners( resolve, reject, file );
                    this._sendRequest( file );
                } ) );
        }

        // Aborts the upload process.
        abort() {
            if ( this.xhr ) {
                this.xhr.abort();
            }
        }

        // Initializes the XMLHttpRequest object using the URL passed to the constructor.
        _initRequest() {
            const xhr = this.xhr = new XMLHttpRequest();

            // Note that your request may look different. It is up to you and your editor
            // integration to choose the right communication channel. This example uses
            // a POST request with JSON as a data structure but your configuration
            // could be different.
            xhr.open( 'POST', '{{ route('about.store') }}', true );
            xhr.setRequestHeader('x-csrf-token', '{{ csrf_token() }}')
            xhr.responseType = 'json';
        }


        // Initializes XMLHttpRequest listeners.
        _initListeners( resolve, reject, file ) {
            const xhr = this.xhr;
            const loader = this.loader;
            const genericErrorText = `Couldn't upload file: ${ file.name }.`;

            xhr.addEventListener( 'error', () => reject( genericErrorText ) );
            xhr.addEventListener( 'abort', () => reject() );
            xhr.addEventListener( 'load', () => {
                const response = xhr.response;

                // This example assumes the XHR server's "response" object will come with
                // an "error" which has its own "message" that can be passed to reject()
                // in the upload promise.
                //
                // Your integration may handle upload errors in a different way so make sure
                // it is done properly. The reject() function must be called when the upload fails.
                if ( !response || response.error ) {
                    return reject( response && response.error ? response.error.message : genericErrorText );
                }

                // If the upload is successful, resolve the upload promise with an object containing
                // at least the "default" URL, pointing to the image on the server.
                // This URL will be used to display the image in the content. Learn more in the
                // UploadAdapter#upload documentation.
                resolve( {
                    default: response.url
                } );
            } );

            // Upload progress when it is supported. The file loader has the #uploadTotal and #uploaded
            // properties which are used e.g. to display the upload progress bar in the editor
            // user interface.
            if ( xhr.upload ) {
                xhr.upload.addEventListener( 'progress', evt => {
                    if ( evt.lengthComputable ) {
                        loader.uploadTotal = evt.total;
                        loader.uploaded = evt.loaded;
                    }
                } );
            }
        }

         // Prepares the data and sends the request.
        _sendRequest( file ) {
            // Prepare the form data.
            const data = new FormData();

            data.append( 'upload', file );

            // Important note: This is the right place to implement security mechanisms
            // like authentication and CSRF protection. For instance, you can use
            // XMLHttpRequest.setRequestHeader() to set the request headers containing
            // the CSRF token generated earlier by your application.

            // Send the request.
            this.xhr.send( data );
        }

        // ...
    }

    function SimpleUploadAdapterPlugin( editor ) {
        editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
            // Configure the URL to the upload script in your back-end here!
            return new MyUploadAdapter( loader );
        };
    }

    ClassicEditor
        .create( document.querySelector( '#About' ), {

        extraPlugins: [ SimpleUploadAdapterPlugin ],

        mediaEmbed: {
            previewsInData: true
        },

        image: {
            // You need to configure the image toolbar, too, so it uses the new style buttons.
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],

            styles: [
                // This option is equal to a situation where no style is applied.
                'full',

                // This represents an image aligned to the left.
                'alignLeft',

                // This represents an image aligned to the right.
                'alignRight',
            ]
        }
        }).catch( error => {
            console.error( error );
        });



  function showBannerImage(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#AboutBannerImg').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
</script>