routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Removing/Avoiding Register & Password Reset functionality 
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});

Route::get('/password/reset', function() {
    return redirect('/login');
});

Route::post('/password/reset', function() {
    return redirect('/login');
});



Route::prefix('admin')->group(function () {

    Route::resource('about', 'AboutController', [
        'names' => 'about',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('advertise', 'AdvertiseController', [
        'names' => 'advertise',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('businessRegistration', 'BusinessRegistrationController', [
        'names' => 'businessRegistration',
        'except' => [
            'show',
        ]
    ]);

    Route::resource('businessCategory', 'BusinessCategoryController', [
        'names' => 'businessCategory',
        'except' => [
            'show',
        ]
    ]);


    Route::resource('coupon', 'CouponController', [
        'names' => 'coupon',
        'except' => [
            'show',
        ]
    ]);


     Route::resource('page', 'PageController', [
        'names' => 'page',
        'except' => [
            'show',
        ]
    ]);


    Route::post('imageUploadCK', 'PageController@imageUploadCK')->name('imageUploadCK');


    // Route for Show Change Password form and change user Password
    Route::get('changePassword', 'HomeController@showChangePassword')->name('showChangePassword');
    Route::post('changePassword', 'HomeController@changePassword')->name('changeDefaultPassword');
});

resources/views/layouts/partials/footer.blade.php
<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> {{ date('Y') }} &copy; Monster Mailer. Brought to you by <a href="">3G Media Solutions</a> </div>
</div>

<!--end-Footer-part-->

resources/views/layouts/partials/head.blade.php
<head>
<title>Monster Mailer: @yield('title')</title>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/bootstrap.min.css') }}" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/bootstrap-responsive.min.css') }}" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/datepicker.css') }}" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/select2.css') }}" />
{{-- <link rel="stylesheet" href="{{ asset('adminAssets/css/fullcalendar.css') }}" /> --}}
<link rel="stylesheet" href="{{ asset('adminAssets/css/matrix-style.css') }}" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/matrix-media.css') }}" />
<link href="{{ asset('adminAssets/font-awesome/css/font-awesome.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ asset('adminAssets/css/jquery.gritter.css') }}" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="{{ asset('adminAssets/js/jquery.min.js') }}"></script> 
</head>

resources/views/layouts/partials/navbar.blade.php
<!--Header-part-->
<div id="header">
  <a href="{{ route('home') }}">
    <img src="{{ asset('adminAssets/img/logo.png') }}" alt="Monster_Mailer_Logo" width="3.5%" class="logo-position" />
  </a>
</div>
<!--close-Header-part--> 


<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">Welcome  {{ Auth::user()->name }}</span><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <a href="{{ route('showChangePassword') }}"><i class="fa fa-unlock-alt"></i> Change Password</a>
        </li>
        <li class="divider"></li>
        <li>
          <a class="dropdown-item" href="{{ route('logout') }}"
             onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
             <i class="icon-key"></i> {{ __('Logout') }}
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
              @csrf
          </form>

        </li>
      </ul>
    </li>

  </ul>
</div>
<!--close-top-Header-menu-->

resources/views/layouts/partials/scripts.blade.php
{{-- <script src="{{ asset('adminAssets/js/excanvas.min.js') }}"></script>  --}}
{{-- <script src="{{ asset('adminAssets/js/jquery.min.js') }}"></script>  --}}
<script src="{{ asset('adminAssets/js/jquery.ui.custom.js') }}"></script> 
<script src="{{ asset('adminAssets/js/bootstrap.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/bootstrap-datepicker.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.flot.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.flot.resize.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.peity.min.js') }}"></script> 

{{-- <script src="{{ asset('adminAssets/js/fullcalendar.min.js') }}"></script> --}} 
<script src="{{ asset('adminAssets/js/matrix.js') }}"></script> 
<script src="{{ asset('adminAssets/js/matrix.dashboard.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.gritter.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/matrix.interface.js') }}"></script> 
{{-- <script src="{{ asset('adminAssets/js/matrix.chat.js') }}"></script>  --}}

<script src="{{ asset('adminAssets/js/jquery.validate.js') }}"></script> 
<script src="{{ asset('adminAssets/js/matrix.form_validation.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.wizard.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.uniform.js') }}"></script>

<script src="{{ asset('adminAssets/js/select2.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/matrix.popover.js') }}"></script> 
<script src="{{ asset('adminAssets/js/jquery.dataTables.min.js') }}"></script> 
<script src="{{ asset('adminAssets/js/matrix.tables.js') }}"></script> 

<script type="text/javascript">
  // This function is called from the pop-up menus to transfer to
  // a different page. Ignore if the value returned is a null string:
  function goPage (newURL) {

      // if url is empty, skip the menu dividers and reset the menu selection to default
      if (newURL != "") {
      
          // if url is "-", it is this page -- reset the menu:
          if (newURL == "-" ) {
              resetMenu();            
          } 
          // else, send page to designated URL            
          else {  
            document.location.href = newURL;
          }
      }
  }

// resets the menu selection upon entry to this page:
function resetMenu() {
   document.gomenu.selector.selectedIndex = 2;
}
</script>

resources/views/layouts/partials/sidebar.blade.php
<!--sidebar-menu-->
<div id="sidebar">
  <a href="{{ route('home') }}" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>

  <ul>
    <li class="{{ substr(Route::current()->getName(),0,4)=='home' ? 'active' : '' }}">
      <a href="{{ route('home') }}"><i class="icon icon-home"></i> <span>Dashboard</span></a>
    </li>
    

    <li class="submenu {{ substr(Route::current()->getName(),0,6)=='about.' || substr(Route::current()->getName(),0,10)=='advertise.' ? 'active open' : '' }}"> 

      <a href="#"><i class="icon icon-th-list"></i> <span>CMS Management</span></a>
      <ul>
        <li class="{{ substr(Route::current()->getName(),0,6)=='about.' ? 'active' : '' }}">
          <a href="{{ route('about.index') }}">Manage About Us</a>
        </li>

        <li class="{{ substr(Route::current()->getName(),0,10)=='advertise.' ? 'active' : '' }}">
          <a href="{{ route('advertise.index') }}">Manage Advertise</a>
        </li>
      </ul>
    </li>
 
    <li class="submenu {{ substr(Route::current()->getName(),0,21)=='businessRegistration.' || substr(Route::current()->getName(),0,17)=='businessCategory.' ? 'active open' : '' }}"> 
      <a href="#"><i class="icon icon-file"></i> <span>Listing Management</span></a>
      <ul>

        <li class="{{ substr(Route::current()->getName(),0,17)=='businessCategory.' ? 'active' : '' }}">
          <a href="{{ route('businessCategory.index') }}">Manage Business Category</a>
        </li>

        <li class="{{ substr(Route::current()->getName(),0,21)=='businessRegistration.' ? 'active' : '' }}">
          <a href="{{ route('businessRegistration.index') }}">Manage CTA</a>
        </li>
      </ul>
    </li>

    <li class="submenu {{ substr(Route::current()->getName(),0,7)=='coupon.' ? 'active open' : '' }}"> 
      <a href="#"><i class="icon icon-info-sign"></i> <span>Coupon Management</span></a>
      <ul>
        <li class="{{ substr(Route::current()->getName(),0,7)=='coupon.' ? 'active' : '' }}">
          <a href="{{ route('coupon.index') }}">Manage Coupons</a>
        </li>
      </ul>
    </li>

     <li class="submenu {{ substr(Route::current()->getName(),0,5)=='page.' ? 'active open' : '' }}"> 
      <a href="#"><i class="icon icon-file"></i> <span>Page Management</span></a>
      <ul>
        <li class="{{ substr(Route::current()->getName(),0,5)=='page.' ? 'active' : '' }}">
          <a href="{{ route('page.index') }}">Manage Pages</a>
        </li>
      </ul>
    </li>
    
  </ul>
</div>
<!--sidebar-menu-->