routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Removing/Avoiding Register & Password Reset functionality 
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});

Route::get('/password/reset', function() {
    return redirect('/login');
});

Route::post('/password/reset', function() {
    return redirect('/login');
});



Route::prefix('admin')->group(function () {

    Route::resource('about', 'AboutController', [
        'names' => 'about',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('advertise', 'AdvertiseController', [
        'names' => 'advertise',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('businessRegistration', 'BusinessRegistrationController', [
        'names' => 'businessRegistration',
        'except' => [
            'show',
        ]
    ]);

    Route::resource('businessCategory', 'BusinessCategoryController', [
        'names' => 'businessCategory',
        'except' => [
            'show',
        ]
    ]);


    Route::resource('coupon', 'CouponController', [
        'names' => 'coupon',
        'except' => [
            'show',
        ]
    ]);


     Route::resource('page', 'PageController', [
        'names' => 'page',
        'except' => [
            'show',
        ]
    ]);


    Route::post('imageUploadCK', 'PageController@imageUploadCK')->name('imageUploadCK');


    // Route for Show Change Password form and change user Password
    Route::get('changePassword', 'HomeController@showChangePassword')->name('showChangePassword');
    Route::post('changePassword', 'HomeController@changePassword')->name('changeDefaultPassword');
});

resources/views/admin/pages/create.blade.php
@extends('layouts.master')

@section('title', 'Create Page')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('page.index') }}" title="Go to Page" class="tip-bottom">
        <i class="icon-home"></i> Create Page</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  
<div class="container-fluid margin-top-2">
    <form action="{{route('page.store')}}" method="POST" class="form-horizontal" autocomplete="off" enctype="multipart/form-data">
    @csrf
    
      @include('admin.pages.form')
        
    </form>
</div>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Page')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('page.index') }}" title="Go to Page" class="tip-bottom">
        <i class="icon-home"></i> Edit Page</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  
<div class="container-fluid margin-top-2">
    <form action="{{route('page.update', $page)}}" method="POST" class="form-horizontal" enctype="multipart/form-data">
      @csrf
      @method('PATCH')
    
      @include('admin.pages.form')
        
    </form>
</div>

@endsection

resources/views/admin/pages/form.blade.php
<style>
.ck-editor__editable_inline {
    min-height: 400px;
}

.ck.ck-editor {
    max-width: 67rem;
}
</style>

<div class="widget-box">
      <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
        <h5>Page SEO setup</h5>
      </div>

        <div class="control-group">
          <label class="control-label">Meta Title :</label>
          <div class="controls">
            <input type="text" 
                   name="meta_title" 
                   class="span11" 
                   placeholder="Meta Title" 
                   value="{{old('meta_title', isset($page) ? $page->meta_title:'')}}" 
                   required />

            @error('meta_title')
              <p class="alert alert-error custom-error">
                <strong>{{ $message }}</strong>
              </p>
            @enderror
          </div>
        </div>

      <div class="control-group">
        <label class="control-label">Meta Keyword :</label>
        <div class="controls">
          <textarea class="span11" name="meta_keyword" rows="4" placeholder="Meta Keyword">{{old('meta_keyword', isset($page) ? $page->meta_keyword:'')}}</textarea>

          @error('meta_keyword')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>


      <div class="control-group">
        <label class="control-label">Meta Description :</label>
        <div class="controls">
          <textarea class="span11" name="meta_description" rows="5" placeholder="Meta Description">{{old('meta_description', isset($page) ? $page->meta_description:'')}}</textarea>

          @error('meta_description')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>



  <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
    <h5>Page Details</h5>
  </div>


  <div class="widget-content nopadding">
      <div class="control-group">
        <label class="control-label">Page Name :</label>
        <div class="controls">
          <input type="text" 
                 name="name" 
                 class="span11 uppercese" 
                 placeholder="Page Name" 
                 value="{{old('name', isset($page) ? $page->name:'')}}" 
                 required />

          @error('name')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Banner Title :</label>
        <div class="controls">
          <input type="text" 
                 name="banner_title" 
                 class="span11" 
                 placeholder="Banner Title" 
                 value="{{old('banner_title', isset($page) ? $page->banner_title:'')}}" 
                 required />

          @error('banner_title')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>

    
      <div class="control-group">
        <label class="control-label">Short Description :</label>
        <div class="controls">
          <textarea class="span11" name="short_description" rows="5">{{old('short_description', isset($page) ? $page->short_description:'')}}</textarea>

          @error('short_description')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>


      <div class="control-group">
        <label class="control-label">Banner Image</label>
        <div class="controls">
          <input type="file" name="banner_image" accept="image/*" onchange="showBannerImage(this)" />

          @error('banner_image')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror

         <img src="{{  isset($page->banner_image) ? Storage::url($page->banner_image) : asset('adminAssets/img/default-org.png') }}"
                   id="BannerImg"
                   class="frame frame-1"
                   title="Banner Image"
                   alt="banner_image">
        </div>


      </div>

     

      <div class="control-group">
        <label class="control-label">Page Content :</label>
        <div class="controls">
          <textarea class="span11" name="content" id="PageContent" rows="4">{{old('content', isset($page) ? $page->content:'')}}</textarea>

          @error('content')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>


      <div class="form-actions">
        <button type="submit" class="btn btn-success"> {{isset($page) ? 'Update' : 'Create'}}</button>
        <a href="{{ route('page.index') }}" class="btn btn-danger">Cancel</a>
      </div>
  </div>
</div>



<script src="{{ asset('adminAssets/plugins/ckeditor5/ckeditor.js') }}"></script>
<script src="{{ asset('adminAssets/js/custom/page.js') }}"></script>

@include('admin.pages.scripts')

resources/views/admin/pages/list.blade.php
@extends('layouts.master')

@section('title', 'Page Listing')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('page.index') }}" title="Go to Page Listing" class="tip-bottom">
        <i class="icon-home"></i> Page Listing</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  <div class="container-fluid">
    <a href="{{ route('page.create') }}" class="btn btn-success btn-create">Create New Page</a>
        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5>Page List</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Meta Title</th>
                  <th width="15%">Status</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                @if($pages->count() > 0 )
                  @foreach($pages as $page)
                    <tr class="odd gradeX">
                      <td class="align-center">
                          {{ $page->name }}
                      </td>
                      <td class="align-center">
                          {{ $page->meta_title }}
                      </td>
                    
                       <td>
                        <div class="dropdown action-label">
                          <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">

                            <?=(isset($page->status) && $page->status=='active')?'<i class="fa fa-dot-circle-o text-success"></i> Active':'<i class="fa fa-dot-circle-o text-danger"></i> Inactive';?>

                            <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu">
                              <form action="{{route('page.destroy', $page->id)}}" 
                                  method="POST" 
                                  >
                                  @csrf
                                  @method('DELETE')
                                   <button type="submit" 
                                        class="dropdown-item status-btn" 
                                        style="cursor: pointer;">
                                    
                                    {!! ($page->status=='active')? "<i class='fa fa-dot-circle-o text-danger'></i> Inactive":"<i class='fa fa-dot-circle-o text-success'></i> Active" !!}
                                  </button>
                              </form>
                            </div>
                        </div>
                      </td>
                      
                      <td class="align-center">
                           <a href="{{ route('page.edit', $page) }}" class="btn btn-primary">Edit</a>
                      </td>
                    </tr>
                  @endforeach
                @else
                  <td>No Pages found</td>
                @endif
              </tbody>
            </table>
          </div>
        </div>
    </div>

@endsection

resources/views/admin/pages/scripts.blade.php
<script>
    class MyUploadAdapter {
        constructor( loader ) {
            // The file loader instance to use during the upload. It sounds scary but do not
            // worry — the loader will be passed into the adapter later on in this guide.
            this.loader = loader;
        }

        // Starts the upload process.
        upload() {
            return this.loader.file
                .then( file => new Promise( ( resolve, reject ) => {
                    this._initRequest();
                    this._initListeners( resolve, reject, file );
                    this._sendRequest( file );
                } ) );
        }

        // Aborts the upload process.
        abort() {
            if ( this.xhr ) {
                this.xhr.abort();
            }
        }

        // Initializes the XMLHttpRequest object using the URL passed to the constructor.
        _initRequest() {
            const xhr = this.xhr = new XMLHttpRequest();

            // Note that your request may look different. It is up to you and your editor
            // integration to choose the right communication channel. This example uses
            // a POST request with JSON as a data structure but your configuration
            // could be different.
            xhr.open( 'POST', '{{ route('imageUploadCK') }}', true );
            xhr.setRequestHeader('x-csrf-token', '{{ csrf_token() }}')
            xhr.responseType = 'json';
        }


        // Initializes XMLHttpRequest listeners.
        _initListeners( resolve, reject, file ) {
            const xhr = this.xhr;
            const loader = this.loader;
            const genericErrorText = `Couldn't upload file: ${ file.name }.`;

            xhr.addEventListener( 'error', () => reject( genericErrorText ) );
            xhr.addEventListener( 'abort', () => reject() );
            xhr.addEventListener( 'load', () => {
                const response = xhr.response;

                // This example assumes the XHR server's "response" object will come with
                // an "error" which has its own "message" that can be passed to reject()
                // in the upload promise.
                //
                // Your integration may handle upload errors in a different way so make sure
                // it is done properly. The reject() function must be called when the upload fails.
                if ( !response || response.error ) {
                    return reject( response && response.error ? response.error.message : genericErrorText );
                }

                // If the upload is successful, resolve the upload promise with an object containing
                // at least the "default" URL, pointing to the image on the server.
                // This URL will be used to display the image in the content. Learn more in the
                // UploadAdapter#upload documentation.
                resolve( {
                    default: response.url
                } );
            } );

            // Upload progress when it is supported. The file loader has the #uploadTotal and #uploaded
            // properties which are used e.g. to display the upload progress bar in the editor
            // user interface.
            if ( xhr.upload ) {
                xhr.upload.addEventListener( 'progress', evt => {
                    if ( evt.lengthComputable ) {
                        loader.uploadTotal = evt.total;
                        loader.uploaded = evt.loaded;
                    }
                } );
            }
        }

         // Prepares the data and sends the request.
        _sendRequest( file ) {
            // Prepare the form data.
            const data = new FormData();

            data.append( 'upload', file );

            // Important note: This is the right place to implement security mechanisms
            // like authentication and CSRF protection. For instance, you can use
            // XMLHttpRequest.setRequestHeader() to set the request headers containing
            // the CSRF token generated earlier by your application.

            // Send the request.
            this.xhr.send( data );
        }

        // ...
    }

    function SimpleUploadAdapterPlugin( editor ) {
        editor.plugins.get( 'FileRepository' ).createUploadAdapter = ( loader ) => {
            // Configure the URL to the upload script in your back-end here!
            return new MyUploadAdapter( loader );
        };
    }

    ClassicEditor
        .create( document.querySelector( '#PageContent' ), {

        extraPlugins: [ SimpleUploadAdapterPlugin ],

        mediaEmbed: {
            previewsInData: true
        },
        image: {
            // You need to configure the image toolbar, too, so it uses the new style buttons.
            toolbar: [ 'imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],

            styles: [
                // This option is equal to a situation where no style is applied.
                'full',

                // This represents an image aligned to the left.
                'alignLeft',

                // This represents an image aligned to the right.
                'alignRight',
            ]
        }
        }).catch( error => {
            console.error( error );
        });

</script>