routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Removing/Avoiding Register & Password Reset functionality 
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});

Route::get('/password/reset', function() {
    return redirect('/login');
});

Route::post('/password/reset', function() {
    return redirect('/login');
});



Route::prefix('admin')->group(function () {

    Route::resource('about', 'AboutController', [
        'names' => 'about',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('advertise', 'AdvertiseController', [
        'names' => 'advertise',
        'except' => [
            'show',
            'create',
            'destroy'
        ]
    ]);

    Route::resource('businessRegistration', 'BusinessRegistrationController', [
        'names' => 'businessRegistration',
        'except' => [
            'show',
        ]
    ]);

    Route::resource('businessCategory', 'BusinessCategoryController', [
        'names' => 'businessCategory',
        'except' => [
            'show',
        ]
    ]);


    Route::resource('coupon', 'CouponController', [
        'names' => 'coupon',
        'except' => [
            'show',
        ]
    ]);


     Route::resource('page', 'PageController', [
        'names' => 'page',
        'except' => [
            'show',
        ]
    ]);


    Route::post('imageUploadCK', 'PageController@imageUploadCK')->name('imageUploadCK');


    // Route for Show Change Password form and change user Password
    Route::get('changePassword', 'HomeController@showChangePassword')->name('showChangePassword');
    Route::post('changePassword', 'HomeController@changePassword')->name('changeDefaultPassword');
});

app/Models/BusinessCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BusinessCategory extends Model
{
    use HasFactory;

    protected $fillable = ['name','status'];


    public function businessRegistrations()
    {
        return $this->hasMany(BusinessRegistration::class);
    }
}

app/Http/Controllers/BusinessCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\BusinessCategory;
use Illuminate\Http\Request;

class BusinessCategoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['businessCategories'] = BusinessCategory::all();
        return view('admin.businessCategory.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('admin.businessCategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $values = $request->validate([
            'name' => 'required|string|max:150|unique:business_categories,name'
        ]);

        $businessCategory = new BusinessCategory();
        $businessCategory->fill($values);
        $businessCategory->save();

        toast($businessCategory->name . ' Created Successfully!','success');

        return redirect()->route('businessCategory.index');
    }

    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BusinessCategory  $businessCategory
     * @return \Illuminate\Http\Response
     */
    public function edit(BusinessCategory $businessCategory)
    {
        $data['businessCategory'] = $businessCategory;
        return view('admin.businessCategory.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BusinessCategory  $businessCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BusinessCategory $businessCategory)
    {
        $changed = false;
        $values = $request->validate([
            'name' => 'required|string|max:150|unique:business_categories,name,' . $businessCategory->id
        ]);

        $businessCategory->fill($values);
        if ($businessCategory->isDirty()) {
            $changed = true;
            $businessCategory->save();
        }

        if (! $changed) {
            toast('No changes done to save','warning');
            return redirect()->route('businessCategory.index')->withErrors('No changes done to save');
        }

        toast($businessCategory->name . ' Updated Successfully!','success');
        return redirect()->route('businessCategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BusinessCategory  $businessCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(BusinessCategory $businessCategory)
    {
        if ($businessCategory->status == 'active') {
            $businessCategory->status = 'inactive';
        } else {
            $businessCategory->status = 'active';
        }

        $businessCategory->save();
        
        toast($businessCategory->name . ' ' . (($businessCategory->status == 'inactive') ? 'Disabled' : 'Enabled') . ' successfully!','success');

        return redirect()->route('businessCategory.index');
    }
}

resources/views/admin/businessCategory/create.blade.php
@extends('layouts.master')

@section('title', 'Create Business Category')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('businessCategory.index') }}" title="Go to Business Category" class="tip-bottom">
        <i class="icon-home"></i> Create Business Category</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  
<div class="container-fluid margin-top-2">
    <form action="{{route('businessCategory.store')}}" method="POST" class="form-horizontal" autocomplete="off">
    @csrf
    
      @include('admin.businessCategory.form')
        
    </form>
</div>

@endsection

resources/views/admin/businessCategory/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Business Category')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('businessCategory.index') }}" title="Go to Business Category" class="tip-bottom">
        <i class="icon-home"></i> Edit Business Category</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  
<div class="container-fluid margin-top-2">
    <form action="{{route('businessCategory.update', $businessCategory)}}" method="POST" class="form-horizontal">
      @csrf
      @method('PATCH')
    
      @include('admin.businessCategory.form')
        
    </form>
</div>

@endsection

resources/views/admin/businessCategory/form.blade.php
<div class="widget-box">
  <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
    <h5>Create Business Category</h5>
  </div>

  <div class="widget-content nopadding">
      <div class="control-group">
        <label class="control-label">Category Name :</label>
        <div class="controls">
          <input type="text" 
                 name="name" 
                 class="span11" 
                 placeholder="Business Catergory Name" 
                 value="{{old('name', isset($businessCategory) ? $businessCategory->name:'')}}" 
                 required />

          @error('name')
            <p class="alert alert-error custom-error">
              <strong>{{ $message }}</strong>
            </p>
          @enderror
        </div>
      </div>

      <div class="form-actions">
        <button type="submit" class="btn btn-success"> {{isset($businessCategory) ? 'Update' : 'Create'}}</button>
        <a href="{{ route('businessCategory.index') }}" class="btn btn-danger">Cancel</a>
      </div>
  </div>
</div>

resources/views/admin/businessCategory/list.blade.php
@extends('layouts.master')

@section('title', 'Business Category')

@section('content')

<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> 
        <a href="{{ route('home') }}" title="Go to Dashboard" class="tip-bottom">
            <i class="icon-home"></i> Dashboard</a>
        <a href="{{ route('businessCategory.index') }}" title="Go to Business Category" class="tip-bottom">
        <i class="icon-home"></i> Business Category</a>
    </div>
  </div>
<!--End-breadcrumbs-->

  <div class="container-fluid">
    <a href="{{ route('businessCategory.create') }}" class="btn btn-success btn-create">Add New Business Category</a>
        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
            <h5>Business Categoty List</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Category Name</th>
                  <th width="15%">Status</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                @foreach($businessCategories as $businessCategory)
                <tr class="odd gradeX">
                  <td class="align-center">
                      {{ $businessCategory->name }}
                  </td>

                  <td>
                    <div class="dropdown action-label">
                      <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">

                        <?=(isset($businessCategory->status) && $businessCategory->status=='active')?'<i class="fa fa-dot-circle-o text-success"></i> Active':'<i class="fa fa-dot-circle-o text-danger"></i> Inactive';?>

                        <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu">
                          <form action="{{route('businessCategory.destroy', $businessCategory->id)}}" 
                              method="POST" 
                              >
                              @csrf
                              @method('DELETE')
                               <button type="submit" 
                                    class="dropdown-item status-btn" 
                                    style="cursor: pointer;">
                                
                                {!! ($businessCategory->status=='active')? "<i class='fa fa-dot-circle-o text-danger'></i> Inactive":"<i class='fa fa-dot-circle-o text-success'></i> Active" !!}
                              </button>
                          </form>
                        </div>
                    </div>
                  </td>
               
                  <td class="align-center">
                       <a href="{{ route('businessCategory.edit', $businessCategory) }}" class="btn btn-primary">Edit</a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
    </div>

@endsection